# Generated by Django 5.2.4 on 2025-10-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EHRS_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Mob', models.CharField(max_length=15)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(max_length=10)),
                ('Role_name', models.CharField(max_length=50)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
            ],
        ),
    ]
