# Generated by Django 5.2.4 on 2025-10-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EHRS_admin', '0002_register_master'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register_Master',
        ),
    ]
