# Generated by Django 5.2.4 on 2025-08-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Master',
            fields=[
                ('Reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=40, unique=True)),
                ('Mob', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('DOB', models.DateField(default=None)),
                ('Gender', models.CharField(max_length=40)),
                ('Address', models.CharField(max_length=100)),
                ('Role_name', models.CharField(max_length=30)),
                ('Status', models.IntegerField(default=0)),
            ],
        ),
    ]
