# Generated by Django 5.2.4 on 2025-08-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
