# Generated by Django 5.2.4 on 2025-09-06 10:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doct_name', models.CharField(max_length=100)),
                ('doct_contact', models.CharField(max_length=15)),
                ('p_name', models.CharField(max_length=100)),
                ('p_mobile', models.CharField(max_length=15)),
                ('p_adress', models.TextField()),
                ('p_gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('p_disease', models.CharField(max_length=255)),
                ('todaydate', models.DateField(auto_now=True)),
                ('a_date', models.DateField(default=datetime.date.today)),
                ('fromTime', models.TimeField(default=datetime.time(9, 0))),
                ('totime', models.TimeField(default=datetime.time(17, 0))),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('doct_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.register_master')),
            ],
        ),
    ]
