# Generated by Django 5.2.4 on 2025-09-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_appointment',
            old_name='p_adress',
            new_name='p_address',
        ),
    ]
