# Generated by Django 5.2.4 on 2025-09-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_patienttestreort_delete_patient'),
        ('Register', '0001_initial'),
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientTestReort',
            new_name='PatientTestReport',
        ),
    ]
